### ISSUE TITLE
issues runing on local webserver

### ISSUE THREAD

**Issue by deepsalternate** [rodpolako/Chess-PGN-Trainer#1]
HI, rodpolako i came across your post on chess tactics trainer on  Dan heisman guide  on chess.com i appreciated your post and wanted to try the chess pgn trainer . but i couldnt  run it on local webserver .how do i run it locally on my pc . more detailed instructions on how do i run this program locally would be very helpful . Thankyou

**Comment by rodpolako** [comment]
Hello,
   The best option is to just use the live web link if you just want to use it and not bother with hosting an instance yourself.  

Personally, I just used Python to host the page as per the instructions I found here:
https://stackoverflow.com/questions/5050851/best-lightweight-web-server-only-static-content-for-windows

All I do is extract the contents of the release to a folder and then run the following command from that folder:
```python -m http.server 8000```

After that, leave that window open and in a browser go to ```localhost:8000/index.html```.  This is exactly what I do while I develop the app and I've never had to do anything more.  The contents of the release is also the only thing on the live github.io link so that helps to validate that the release itself is good.

If you don't want Python, try googling "free windows web server light".  I tried that and the first hit I found was something called Regex Tiny Web Server (free).  I downloaded that, configured the www folder and started the service and it came right up when I point the browser to it.

I can't really give you more advice on how to host a web page on your own computer, that is up to you.

**Comment by deepsalternate** [comment]
hi, Thanks for your help . i figured it out already the same day after opening the issues .I Apologize that i didnt mention . anyways thanks for your Help .Because of your this program , I find practicing tactics from books  very easy without much hassel (using pgn found online  on Bill Walls chess page  ) and in much efficient way . I believe it will surely help in my elo . Thankyou very much .

**Comment by rodpolako** [comment]
Thanks for letting me know.  I'm glad to hear you got it working.
